spring.application.name=videogame

#Configuracion DB /IMPORTANTE/
#Configurar conexion
spring.datasource.url=jdbc:mysql://localhost:3306/videogamesdb
spring.datasource.username=root
spring.datasource.password=system

#Driver de mysql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#Configuracion de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

##opcional server.port=8080 // se puede cambiar
